### ISSUE TITLE
莫名其妙出现这种状况

### ISSUE THREAD

**Issue by Ryan2206** [malinkang/weread_to_notion#10]
<img width="1263" alt="截屏2023-05-05 23 21 39" src="https://user-images.githubusercontent.com/80443876/236500068-4184b992-1d76-470c-a103-e1d758ebcf49.png">

**Comment by malinkang** [comment]
移除了bs4的依赖，同步下代码试试。

**Comment by Ryan2206** [comment]
好的谢谢开发者
