### ISSUE TITLE
notion里模板里缺少properties

### ISSUE THREAD

**Issue by yukomeoww** [malinkang/weread_to_notion#22]
1. `notion_client.errors.APIResponseError: ISBN is not a property that exists. URL is not a property that exists. Rating is not a property that exists.` 模板缺少这三个新加的property(ISBN, URL, Rating), 需要加到Table properties

2. 教程里缺少notion database  - add connection 这个部分, 不做的话 notion token access 不了database

**Comment by HRITW** [comment]
第2个问题教程里的第5点提到了，第一个问题现在应该如何解决呢？

**Comment by malinkang** [comment]
如果是之前复制的模板，按照新模板里新增这几个Properties即可。
