### ISSUE TITLE
无法实现

### ISSUE THREAD

**Issue by HRITW** [malinkang/weread_to_notion#23]
您好，每一步否按照要求做了，但是无法实现相应的功能。是否因为现在有了新的变化？

**Comment by malinkang** [comment]
建议你重新fork下项目复制下模板，按照教程重新设置一遍。

**Comment by Xiaoshizi1024** [comment]
问题太过笼统了，完全没有参考价值，没有错误怎么会实现不了，至少会出现Bug是啥吧，推荐阅读《提问的智慧》
