### ISSUE TITLE
同步计划一直在进行，但是书库没有变化

### ISSUE THREAD

**Issue by dsdffgh** [malinkang/weread_to_notion#27]
除了第一天成功同步之外，之后connection就完全没有修改过database。不知道是否跟cookie一直在变有关——因为我开了禁广告ADguard。
但是当我把Adguard关掉，更新cookie以后手动同步，页面还是没有变化。我确定token和dataID都是正确的

**Comment by malinkang** [comment]
可以把你的cookie和datebaseid发我，我帮你debug排查下。

**Comment by dsdffgh** [comment]
cookie:
wr_theme=dark; RK=zkmsMS8ZRL; ptcz=88c959a44e795ff6c0cf6ad7703c4120b6ea06a8b5b642bb9543f149e8eef422; wr_localvid=d573203081abf01ffd57f8a; wr_name=_%5Cinf; wr_avatar=https%3A%2F%2Fthirdwx.qlogo.cn%2Fmmopen%2Fvi_32%2FjZFphnk3yRcljFlGcoWI7XzAWRfx07icVQ7ABpyUsEq0uzNv1FIoAp6ZeZSrwOKO8piblWtyGIsaLOUsMYPAzHUg%2F132; wr_gender=1; wr_fp=113160872; iip=0; _qpsvr_localtk=0.4298460655748717; wr_gid=292967569

datebaseid:
e2cda5dec30646f3a185d48a804477bd

**Comment by malinkang** [comment]
别发到这里，泄露你信息了。你加我微信聊吧。微信号：malinkang
