### ISSUE TITLE
更新之后，同步一直出错，Process completed with exit code 1.

### ISSUE THREAD

**Issue by edwardcuchulainn** [malinkang/weread_to_notion#29]
![image](https://github.com/malinkang/weread_to_notion/assets/51317695/d4eb32d9-27fb-4dae-a973-49289545cc53)

**Comment by edwardcuchulainn** [comment]
知道了，因为更新之后模板没对应，缺少相应的列，删除模板重新建一个就好了

**Comment by Xiaoshizi1024** [comment]
what？模板也影响这个？我也是这个错误代码，我去试试~

**Comment by Xiaoshizi1024** [comment]
虽说同是一个错误，但是具体内容是不一样的，我删除把列也删除了...   
通过重新复制模板，重新运行还是不行~
