### ISSUE TITLE
自己上传微信读书里的书不显示封面

### ISSUE THREAD

**Issue by cryueh** [malinkang/weread_to_notion#30]
自己上传到微信读书里的mobi和epub格式受影响，pdf格式的书籍的cover封面显示正常，不受影响。

notion里，其余字段正常获取不受影响，并且bookname前面的图标显示正常，有数据的封面，但cover里为cover的灰色链接：https://wrco-40036.sh.gfp.tencent-cloud.com/CB_EMb3Zh3YK8uJ6i36gwBfz3hn/parsecover?sign=q-sign-algorithm%3Dsha1%26q-ak%3Dcydn1szJ2OQT2J72AOTKL4DZ%26q-sign-time%3D1692166441%3B1692167041%26q-key-time%3D1692166441%3B1692167041%26q-header-list%3Dhost%26q-url-param-list%3D%26q-signature%3D8ac25232101ff8260068cd4e5c79855740080787

于是乎来到weread.qq.com检查，发现mobi和epub的封面链接均为下载文件的形式，pdf则为图片形式。

私以为说明程序是正常跑的，链接也抓到了，只是notion数据里的cover字段是文件和媒体公用字段，链接被notion识别为了文件，故而没有使用图片进行直接展示，至于微信读书里mobi和epub的图片链接为文件格式，可能是有特殊原因存在。

不知道可不可行的胡乱猜想不负责任信口胡说解决方案：
1、微信读书侧生成的链接有没有可能转换为图片形式；
2、notion里关于cvoer字段能否像bookname前面的图标一样直接显示为图片；
3、py检测到链接里包含：parsecover时，下载图片转存到notion，在notion进行显示。

**Comment by cryueh** [comment]
![image](https://github.com/malinkang/weread_to_notion/assets/44696492/a7b8d59e-86fa-4c4b-9a53-c076fc1b5d17)

**Comment by malinkang** [comment]
看了下，发现自己上传的书和微信读书里书封面格式有点区别 https://cdn.weread.qq.com/weread/cover/28/YueWen_31808219/s_YueWen_31808219.jpg
https://res.weread.qq.com/wrepub/CB_AtLGDfGF9EV96i36gYDDjE2J_parsecover
一个带后缀一个不带后缀，测试了下直接拼一个.jpg也可以显示。

**Comment by malinkang** [comment]
另外Notion的api不支持上传文件，所以下载上传到Notion的方案也不行。
<img width="767" alt="image" src="https://github.com/malinkang/weread_to_notion/assets/3365208/2a10a9f8-deb1-4a93-b28a-c14fb52f0525">
https://developers.notion.com/reference/file-object
目前没有太好的办法。
