### ISSUE TITLE
自动化错误疑似cookie格式不对？如何正确获取cookie？

### ISSUE THREAD

**Issue by Xiaoshizi1024** [malinkang/weread_to_notion#34]
具体问题是：
```
Traceback (most recent call last):
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 389, in <module>
    session.get(WEREAD_URL)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/requests/sessions.py", line 719, in send
    extract_cookies_to_jar(self.cookies, request, r.raw)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/requests/cookies.py", line [13](https://github.com/Xiaoshizi1024/weread_to_notion/actions/runs/6439335875/job/17489578613#step:5:14)7, in extract_cookies_to_jar
    jar.extract_cookies(res, req)
AttributeError: 'NoneType' object has no attribute 'extract_cookies'
Error: Process completed with exit code 1.
```
没有对代码做任何改变，那么能错误的只有上传的三个参数，看着应该是cookie的问题。   

自我测试，用edge获取的cookie跟Google Chrome获取的格式竟然都不一样，两个都测试了，但是还是出现同样的错误。   
那么难道是我获取的cookie有问题？   

我是如何获取cookie的？   
- 在网页端，打开开发者选项，随便点击一本书，会出现doc，然后在文件“weread.qq.com”  标头中，请求的标头中获取的。     

![cookie对比](https://github.com/malinkang/weread_to_notion/assets/32703518/9eecb5f2-e535-4474-a5df-7771556bbdd8)   

我具体上传参数格式是这样的   

![setting](https://github.com/malinkang/weread_to_notion/assets/32703518/7201b457-eec3-487e-89be-a0dad65e575d)
这是基本上所有的内容了，我尝试着重新上传这三个参数，但是还没有解决问题，所以希望您能帮助我~

**Comment by Xiaoshizi1024** [comment]
以参考 29将模板错误进行修改，还是不行，但是至少修改了一次错误，删除把列信息都删除完了~

**Comment by Xiaoshizi1024** [comment]
[报错，请求参数有问题？ · Issue #19 · malinkang/weread_to_notion
https://github.com/malinkang/weread_to_notion/issues/19](https://github.com/malinkang/weread_to_notion/issues/21#issuecomment-1622919727) what，三个参数设置错地方了吗？  不懂英语的亏...     
修改完测试，出现新的Bug    
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/notion_client/client.py", line 118, in _parse_response
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://api.notion.com/v1/databases/***/query'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 390, in <module>
    latest_sort = get_sort()
  File "/home/runner/work/weread_to_notion/weread_to_notion/weread.py", line 290, in get_sort
    response = client.databases.query(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/notion_client/client.py", line 194, in request
    return self._parse_response(response)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/notion_client/client.py", line [12](https://github.com/Xiaoshizi1024/weread_to_notion/actions/runs/6439335875/job/17490148131#step:5:13)6, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: API token is invalid.
Error: Process completed with exit code 1.
```

**Comment by Xiaoshizi1024** [comment]
我又回来了~   
重新输出完又出现的新的Bug，O(∩_∩)O哈哈~  真是反复折磨人，但是我在逐渐进步，因为出现了新的BUg~   
``` 
notion_client.errors.APIResponseError: Could not find database with ID: e4148dc1-c30e-4588-821b-6cf1e173e129. Make sure the relevant pages and databases are shared with your integration.
Error: Process completed with exit code 1. 
```  
Claude 告诉我~   

根据错误信息,出现这个错误的原因是Notion API在查找数据库时,使用的数据库ID e4148dc1-c30e-4588-821b-6cf1e173e129 无法找到对应数据库。
这个错误通常有以下几种可能的原因:
1. 数据库ID写错了,应该检查代码中这个ID从何处获取,是否正确。
2. 数据库ID属于另一个用户或团队空间,当前集成没有访问权限。
3. 这个数据库已经被删除了。
4. 该数据库没有与当前的集成授权共享,无法访问。
5. Notion API服务端处理存在问题。
对应解决方法:
1. 打印日志,确认数据库ID的值是否正确。
2. 检查这个数据库所属并确认当前集成是否有访问其的权限。
3. 在Notion页面中检查此数据库是否已被删除。
4. 在要访问的数据库的分享设置中,共享给当前集成。
5. 重试请求或联系Notion支持。
另外,进程退出码1表示程序执行失败,需要检查日志和调试来定位并解决引发的异常问题,使程序能正常执行完成。   

诶，在操作过程中，我将copy的模板删除重新生成了，难道没有重新获取链接？还是因为链接没有公开访问？    
我再去获取一下分享链接试试~

**Comment by Xiaoshizi1024** [comment]
重新获取链接 还是同样的错误~       
哪个是数据库ID？   
- 我重新生成的模板？        
   
当前集成没有访问权限是不应该的，因为都在我的账户里面，那么是不是我在建立集成的时候，修改了原来的部分参数？  可以去试试重新生成集成...

**Comment by Xiaoshizi1024** [comment]
参考  轻松使用Notion API——Notion教程 - 掘金
https://juejin.cn/post/7067108031678545927  为我们的Notion API设置访问令牌     
`最后，为了使我们先前创建的数据库可用于我们的集成，前往Bootcamp工作区。点击页面右上角的共享按钮。选择我们刚刚创建的rc-bootcamp集成。
点击**邀请。**我们的集成现在应该可以访问我们的Bootcamp工作区。
对我们之前创建的Bootcamp Mailing List工作区重复这个过程。`   
在工作区内没有找到集成的选项，那么就最大权限选择    
![image](https://github.com/malinkang/weread_to_notion/assets/32703518/4a5293f1-8736-4402-ab3d-b7b80e6162a6)   

按理来说，这样集成是不是就跟数据库连接到了一块？   
but ,运行后，还是会报错...

**Comment by Xiaoshizi1024** [comment]
唉，暂时选择放弃，期待能被拯救...   

刚才有进行了完全测试  
1. 重置github仓库，删了重新开仓库   
2. 按照流程再次操作，出现同样的错误
3. 新建工作区？  新复制模板，新复制模板建立数据库 以及制作对应仓库的集成 还是出现问题，还是出现同样的错误...     
4. 那我现在着实排查不出来问题了，那可能是Notion的问题吧...

**Comment by Xiaoshizi1024** [comment]
![image](https://github.com/malinkang/weread_to_notion/assets/32703518/13e1fc7d-85b4-406c-b936-743b50c43fc5)
这可能真的不是我的问题，我已经给Notion官方发邮件了，希望能够得到回复...

**Comment by lis1111** [comment]
同样的问题

**Comment by Xiaoshizi1024** [comment]
@lis1111 具体是哪个问题呢？ 我这里面可是好几个问题呢？最后一步的问题吗？如果一样那我就完全放心了~   
``` 
notion_client.errors.APIResponseError: Could not find database with ID: e4148dc1-c30e-4588-821b-6cf1e173e129. Make sure the relevant pages and databases are shared with your integration.
Error: Process completed with exit code 1. 
```

**Comment by lis1111** [comment]
> @lis1111 具体是哪个问题呢？ 我这里面可是好几个问题呢？最后一步的问题吗？如果一样那我就完全放心了~
> 
> ```
> notion_client.errors.APIResponseError: Could not find database with ID: e4148dc1-c30e-4588-821b-6cf1e173e129. Make sure the relevant pages and databases are shared with your integration.
> Error: Process completed with exit code 1. 
> ```

已经解决了 我自己的问题 文件命名错误了 要保持跟教程内的一致  我叫的其他名字

**Comment by Xiaoshizi1024** [comment]
> > @lis1111 具体是哪个问题呢？ 我这里面可是好几个问题呢？最后一步的问题吗？如果一样那我就完全放心了~
> > ```
> > notion_client.errors.APIResponseError: Could not find database with ID: e4148dc1-c30e-4588-821b-6cf1e173e129. Make sure the relevant pages and databases are shared with your integration.
> > Error: Process completed with exit code 1. 
> > ```
> 
> 已经解决了 我自己的问题 文件命名错误了 要保持跟教程内的一致 我叫的其他名字

嗯哼？是数据库ID还是集成的名称吗？这两者应该关系不大吗？你这个修改的是哪个名字？

**Comment by lis1111** [comment]
> > > @lis1111 具体是哪个问题呢？ 我这里面可是好几个问题呢？最后一步的问题吗？如果一样那我就完全放心了~
> > > ```
> > > notion_client.errors.APIResponseError: Could not find database with ID: e4148dc1-c30e-4588-821b-6cf1e173e129. Make sure the relevant pages and databases are shared with your integration.
> > > Error: Process completed with exit code 1. 
> > > ```
> > 
> > 
> > 已经解决了 我自己的问题 文件命名错误了 要保持跟教程内的一致 我叫的其他名字
> 
> 嗯哼？是数据库ID还是集成的名称吗？这两者应该关系不大吗？你这个修改的是哪个名字？

Repository secrets名称
![image](https://github.com/malinkang/weread_to_notion/assets/129823910/d12ae7e9-8001-4b61-9bad-547c813fbcac)

**Comment by Xiaoshizi1024** [comment]
非常感谢，我这个地方没有问题。这个地方的名称当然是不能改的。咱们算是就输入了这三个数据，你把名字改过之后。相当于系统就没有输入了。

> > > > @lis1111 具体是哪个问题呢？ 我这里面可是好几个问题呢？最后一步的问题吗？如果一样那我就完全放心了~
> > > > ```
> > > > notion_client.errors.APIResponseError: Could not find database with ID: e4148dc1-c30e-4588-821b-6cf1e173e129. Make sure the relevant pages and databases are shared with your integration.
> > > > Error: Process completed with exit code 1. 
> > > > ```
> > > 
> > > 
> > > 已经解决了 我自己的问题 文件命名错误了 要保持跟教程内的一致 我叫的其他名字
> > 
> > 
> > 嗯哼？是数据库ID还是集成的名称吗？这两者应该关系不大吗？你这个修改的是哪个名字？
> 
> Repository secrets名称 ![image](https://user-images.githubusercontent.com/129823910/273445242-d12ae7e9-8001-4b61-9bad-547c813fbcac.png)

非常感谢，我这个地方没有问题。这个地方的名称当然是不能改的。咱们算是就输入了这三个数据，你把名字改过之后。相当于整个系统就没有输入了。那就完全不用了。

**Comment by malinkang** [comment]
![image](https://github.com/malinkang/weread_to_notion/assets/3365208/9ead046a-07c0-4b89-886c-8be44bddf2c9)

**Comment by malinkang** [comment]
搞了个微信群，
![image](https://github.com/malinkang/weread_to_notion/assets/3365208/67b87b3a-29b7-4c0a-879c-dfb3f0a71412)

**Comment by Xiaoshizi1024** [comment]
在Notion官方的帮助下，终于发现问题所在了。
问题在于：没有将集成添加到对应的数据库中，    

如何添加？
- 
![image](https://github.com/malinkang/weread_to_notion/assets/32703518/980c605a-6f1d-4132-b585-f60695ffe91d)

**Comment by Xiaoshizi1024** [comment]
英文版截图，xiwh希望能够帮助到你...      

![image](https://github.com/malinkang/weread_to_notion/assets/32703518/587f83da-af6c-4eb9-b17d-2fb64fae4777)
