### ISSUE TITLE
notion的内容无法更改

### ISSUE THREAD

**Issue by MaDangyang** [malinkang/weread_to_notion#36]
![image](https://github.com/malinkang/weread_to_notion/assets/133070903/5ec9ae37-4637-45a4-af4f-096b668880b0)

例如，当我的微信读书的章节题目变成乱码时，Notion也自动提取了错误题目，无法更改题目。
![image](https://github.com/malinkang/weread_to_notion/assets/133070903/11b8c9af-2902-467f-9103-a7974cc0c4f7)

**Comment by malinkang** [comment]
这个没办法解决，这个工具是纯搬运数据。
