### ISSUE TITLE
运行报错"Process completed with exit code 1"

### ISSUE THREAD

**Issue by AbelHIT** [malinkang/weread_to_notion#37]
无法同步，报错如标题

**Comment by malinkang** [comment]
微信加我：malinkang，把你的cookie发我，我debug下看看

**Comment by AbelHIT** [comment]
刚才又试了几次，最后一次提示"notion_client.errors.APIResponseError: Could not find sort property with name or id: Sort"
且微信已加，烦请通过

**Comment by malinkang** [comment]
已经解决了，我关了。
