### ISSUE TITLE
同步失败

### ISSUE THREAD

**Issue by isisilele** [malinkang/weread_to_notion#38]
Sync报如下错误
Run python weread.py "***" "***" "***" 
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/notion_client/client.py", line [11](https://github.com/isisilele/weread_to_notion/actions/runs/6794084867/job/18469955254#step:5:12)8, in _parse_response
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/httpx/_models.py", line 758, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/databases/***/query'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

看起来是Secrets没有获取到？但在fork的代码中按照guide添加了3个token的。

**Comment by isisilele** [comment]
NotionDatabaseID = 6c038898dfbf43f8a87bc6558e04b8c0
访问https://[api.notion.com/v1/databases/6c038898dfbf43f8a87bc6558e04b8c0/query]
报如下错误
{
    "object": "error",
    "status": 400,
    "code": "invalid_request_url",
    "message": "Invalid request URL."
}

**Comment by isisilele** [comment]
Notion token:"secret_4n6skYURVlwj1ahC4ziQTpx8TpXB0x3eUDWv8gMRDol"

**Comment by malinkang** [comment]
看了下你的模板好像不对，你重新复制下模板，然后重新填写一下database id试试

**Comment by isisilele** [comment]
重新复制模板后个人database地址：_https://www.notion.so/sisilele/1841536fda8f489187c8ef9d0d868a5e?v=0f8b73ec86824255b449f5b5dc67279a_
本地运行代码
python weread.py "iip=0; wr_gid=252795870; pgv_pvid=3489385523; tvfe_boss_uuid=b05596fc98ead1e5;RK=6RNoosgoZw; ptcz=1afc892756f4248dc7a5ea1b25b6d9b3da813589b7beda2938fdb4051b7a3f41;qq_domain_video_guid_verify=bc8c1d63610f0d6c; wr_theme=dark; pac_uid=1_672342901; wr_vid=15560104;wr_pf=0; wr_rt=web%40Q~vEsN2LP9IkTk4rDBN_AL; wr_localvid=a2932b806ed6da8a29f92a1;wr_name=%E5%88%98%E8%82%96; wr_avatar=https%3A%2F%2Fthirdwx.qlogo.cn%2Fmmopen%2Fvi_32%2FZVBHghNC7xdHqjmHls7PjkgtkXgYypga9uY9JrziaBVKUGVPibapUoe2YB5DPT89us3ic9oSuPULaFH8fPGFXnsWQ%2F132; wr_gender=1; wr_fp=826060412; wr_skey=gRG3Qf8G" 
     _**_"secret_4n6skYURVlwj1ahC4ziQTpx8TpXB0x3eUDWv8gMRDol"_**_                   **"1841536fda8f489187c8ef9d0d868a5e"**
报错如下
**httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/databases/1841536fda8f489187c8ef9d0d868a5e/query'**

看起来是调用notion client API进行database query时出错，已经复制了几次模板，均为同样的错误。

**Comment by malinkang** [comment]
把你的notion database 分享一下

**Comment by isisilele** [comment]
地址：https://sisilele.notion.site/1841536fda8f489187c8ef9d0d868a5e?v=0f8b73ec86824255b449f5b5dc67279a&pvs=4
谢谢。

**Comment by malinkang** [comment]
你这个数据结构明显跟我的模板不一致啊 https://malinkang.notion.site/e27842548a6d4a81bc7aea736d90d6dd?v=b255858d3eaa409f97f1ecb32a14a5b6&pvs=4

**Comment by isisilele** [comment]
重新复制模板后还是失败。
在网页端重新新建integration，使用新建的integration token后，sync成功，感谢。
