### ISSUE TITLE
第一次运行同步只同步了几本书，其他统统没有同步

### ISSUE THREAD

**Issue by anuxs** [malinkang/weread_to_notion#7]
第一次成功运行action，只同步成功了3本书。有两本是今天读，一本是昨天读的。但是更早之前的笔记就没有更新了。
其他的书都还是复制过来的模版中的读书笔记，不是我自己的。
现在笔记条数是124，同步之前是121。
看了action的日子，同步已经运行结束正确退出了。

**Comment by malinkang** [comment]
嗯 你把database里的都删掉，重新同步一次就好了。
