### ISSUE TITLE
请问能否实现只要在书架的书就可以同步

### ISSUE THREAD

**Issue by xfxue** [malinkang/weread_to_notion#8]
我发现，需要微信读书上有自己的划线或者笔记才可以同步，请问能否实现不需要划线和笔记，只要在书架的书就可以同步呢？

**Comment by xfxue** [comment]
> 请问，我配置完之后手动同步，notion页面一直没有显示我读的书，该怎么解决啊

现在能同步了，需要微信读书上有自己的划线或者笔记才可以，我想问能不能实现不需要划线和笔记，只要在书架的书就同步过来呢？

**Comment by malinkang** [comment]
我也觉得没必要，这个项目的目的就是同步笔记和划线的，只把书架上的书同步过来没什么用。
